// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqccciddkqzhihhktslm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxY2NjaWRka3F6aGloaGt0c2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTAzMzEsImV4cCI6MjA2OTk2NjMzMX0.H1JMP59v2xdJUGXBTs6L-kCJt1AzxibK6ApQw89hn0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});